apiVersion: v1
kind: Service
metadata:
  name: main-servlet-service
spec:
  selector:
    app: main-servlet
  ports: 
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000
  type: NodePort
      
  